<?php

namespace App\Controller\Admin;

use App\Entity\Banner;
use Doctrine\ORM\EntityManagerInterface;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\DateTimeField;
use EasyCorp\Bundle\EasyAdminBundle\Field\IdField;
use EasyCorp\Bundle\EasyAdminBundle\Field\ImageField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextEditorField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;
use League\Flysystem\FilesystemOperator;

class BannerCrudController extends AbstractCrudController
{
    private FilesystemOperator $s3Storage;

    public function __construct(FilesystemOperator $s3Storage)
    {
        $this->s3Storage = $s3Storage;
    }

    public static function getEntityFqcn(): string
    {
        return Banner::class;
    }


    public function configureFields(string $pageName): iterable
    {
        $uploadDir = $this->getParameter('kernel.environment') === 'dev' ? 'tmp' : '/tmp';
        yield TextField::new('url')
            ->setLabel('URL');

        yield DateTimeField::new('createdAt')
            ->setLabel('Created At')
            ->hideOnForm();

        yield DateTimeField::new('updatedAt')
            ->setLabel('Updated At')
            ->hideOnForm();

        $imageField = ImageField::new('img')
            ->setLabel('Image')
            ->setHelp('Upload will be stored in the S3 bucket in the banner directory.')
            ->setUploadDir($uploadDir)
            ->setBasePath('https://discount-bg.s3.eu-north-1.amazonaws.com/banner/');

        if (Crud::PAGE_EDIT === $pageName) {
            $imageField->setRequired(false); // Ensure it's not mandatory during edit
        }

        yield $imageField;

    }

    public function persistEntity(EntityManagerInterface $entityManager, $entityInstance): void
    {

        if ($entityInstance instanceof Banner) {
            $now = new \DateTimeImmutable();
            $nowMutable = new \DateTime();
            $entityInstance->setCreatedAt($now);
            $entityInstance->setUpdatedAt($nowMutable); // Set updatedAt as well on creation
        }

        parent::persistEntity($entityManager, $entityInstance);

        $uploadedFile = $this->getContext()->getRequest()->files->get('Banner')['img']['file'];

        if ($uploadedFile) {
            $originalFileName = $uploadedFile->getClientOriginalName();

            $filePath = "banner/$originalFileName";
            $projectRoot = $this->getParameter('kernel.project_dir');

            $uploadDir = $this->getParameter('kernel.environment') === 'dev' ? $projectRoot . '/tmp/' : '/tmp';
            $vanishFilePath = $uploadDir . $uploadedFile->getClientOriginalName();
            
            $this->s3Storage->write($filePath, file_get_contents($vanishFilePath));
            $entityInstance->setImg($filePath); // Update the S3 path in the entity

            unlink($vanishFilePath);
        }
    }

    // Override updateEntity to set updatedAt on update
    public function updateEntity(EntityManagerInterface $entityManager, $entityInstance): void
    {
        if ($entityInstance instanceof Banner) {
            $now = new \DateTime();
            $entityInstance->setUpdatedAt($now); // Set updatedAt on every update
        }

        parent::updateEntity($entityManager, $entityInstance);
    }

    public function deleteEntity(EntityManagerInterface $entityManager, $entityInstance): void
    {
        $filePath = 'banner/' . $entityInstance->getImg();
        if ($this->s3Storage->fileExists($filePath)) {
            $this->s3Storage->delete($filePath);
        }
        parent::deleteEntity($entityManager, $entityInstance); // TODO: Change the autogenerated stub
    }

}
