<?php

namespace App\Controller\Admin;

use App\Entity\Banner;
use Doctrine\ORM\EntityManagerInterface;
use EasyCorp\Bundle\EasyAdminBundle\Config\Crud;
use EasyCorp\Bundle\EasyAdminBundle\Controller\AbstractCrudController;
use EasyCorp\Bundle\EasyAdminBundle\Field\DateTimeField;
use EasyCorp\Bundle\EasyAdminBundle\Field\IdField;
use EasyCorp\Bundle\EasyAdminBundle\Field\ImageField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextEditorField;
use EasyCorp\Bundle\EasyAdminBundle\Field\TextField;
use EasyCorp\Bundle\EasyAdminBundle\Form\Type\FileUploadType;
use League\Flysystem\FilesystemOperator;
use Symfony\Component\Form\Extension\Core\Type\FileType;

class BannerCrudController extends AbstractCrudController
{
    private FilesystemOperator $s3Storage;

    public function __construct(FilesystemOperator $s3Storage)
    {
        $this->s3Storage = $s3Storage;
    }

    public static function getEntityFqcn(): string
    {
        return Banner::class;
    }


    public function configureFields(string $pageName): iterable
    {
        $uploadDir = $this->getParameter('kernel.environment') === 'dev' ? 'tmp' : '/tmp';
        yield TextField::new('url')
            ->setLabel('URL');

        yield DateTimeField::new('createdAt')
            ->setLabel('Created At')
            ->hideOnForm();

        yield DateTimeField::new('updatedAt')
            ->setLabel('Updated At')
            ->hideOnForm();

        $imageField = TextField::new('img')
            ->setLabel('Image')
            ->setFormType(FileType::class);
//            ->setHelp('Upload will be stored in the S3 bucket in the banner directory.')
//            ->setBasePath('https://discount-bg.s3.eu-north-1.amazonaws.com/banner/');

        if (Crud::PAGE_EDIT === $pageName) {
            $imageField->setRequired(false); // Ensure it's not mandatory during edit
        }

        yield $imageField;

        if($this->getContext()->getRequest()->files->get('Banner')) {

            $uploadedFile = $this->getContext()->getRequest()->files->get('Banner')['img'];

            if ($uploadedFile) {
                $originalFileName = pathinfo($uploadedFile->getClientOriginalName(), PATHINFO_FILENAME);
                $newFileName = $originalFileName . '.' . $uploadedFile->guessExtension();

                $filePath = "banner/$newFileName";

                $this->s3Storage->write($filePath, file_get_contents($uploadedFile->getPathname()));
            }
        }
    }

    public function persistEntity(EntityManagerInterface $entityManager, $entityInstance): void
    {

        if ($entityInstance instanceof Banner) {
            $now = new \DateTimeImmutable();
            $nowMutable = new \DateTime();
            $entityInstance->setCreatedAt($now);
            $entityInstance->setUpdatedAt($nowMutable); // Set updatedAt as well on creation
            $uploadedFile = $this->getContext()->getRequest()->files->get('Banner')['img'];
            $entityInstance->setImg($uploadedFile->getClientOriginalName());
        }

        parent::persistEntity($entityManager, $entityInstance);
    }

    // Override updateEntity to set updatedAt on update
    public function updateEntity(EntityManagerInterface $entityManager, $entityInstance): void
    {
        if ($entityInstance instanceof Banner) {
            $now = new \DateTime();
            $entityInstance->setUpdatedAt($now); // Set updatedAt on every update
        }

        parent::updateEntity($entityManager, $entityInstance);
    }

    public function deleteEntity(EntityManagerInterface $entityManager, $entityInstance): void
    {
        $filePath = 'banner/' . $entityInstance->getImg();
        if ($this->s3Storage->fileExists($filePath)) {
            $this->s3Storage->delete($filePath);
        }
        parent::deleteEntity($entityManager, $entityInstance); // TODO: Change the autogenerated stub
    }

}
