name: Deploy to Droplet

on:
  push:
    branches:
      - main  # Deploy on push to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to DigitalOcean Droplet
        run: |
          ssh -o StrictHostKeyChecking=no root@209.38.253.172 <<EOF
            cd discountBg  # Navigate to your project on the droplet
            git pull origin main      # Pull the latest code
            docker-compose down       # Stop the running containers
            docker-compose up -d --build  # Rebuild and restart containers
          EOF
